### PR TITLE
Bump levelgraph dependency to ^2.0.0

### LINKED ISSUE #20: Version bump for LevelGraph v2 compatibility?
I'm using both this and `levelgraph-jsonld` together on [LevelGraph Playground](http://github.com/bigbluehat/levelgraph-playground). However, this one's not quite ready for today's LevelGraph 2.x release.

NPM says:
```
npm ERR! peerinvalid The package levelgraph@2.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer levelgraph-jsonld@1.0.0 wants levelgraph@^2.0.0
npm ERR! peerinvalid Peer levelgraph-n3@1.2.0 wants levelgraph@>= 1.0 < 2.0
```

Maybe the `package.json` just needs a tweak?

/cc @jmatsushita

Thanks!
🎩

### PR DESCRIPTION
**Pull request by BigBlueHat**
Fix #20

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing.

**Comment by BigBlueHat** [comment]
All three look like Travis mess ups (afaict).

For instance 0.12 and 4.0 are throwing this error (only finding `levelgraph@1.3.1`):
https://travis-ci.org/mcollina/levelgraph-n3/jobs/191365305#L179

The 0.10 run failed trying to `make` leveldown...
https://travis-ci.org/mcollina/levelgraph-n3/jobs/191365303#L230

Strangeness.

**Comment by mcollina** [comment]
Can you remove node v0.10 and v0.12 from `.travis.yml`? We just need to test on 4, 6, and 7.

**Comment by BigBlueHat** [comment]
Sorry for the wait @mcollina. Here's where Travis is unhappy:
https://travis-ci.org/mcollina/levelgraph-n3/jobs/195687992#L179

**Comment by mcollina** [comment]
@BigBlueHat you should replace level-test with memdb 
https://github.com/BigBlueHat/levelgraph-n3/blob/5aa5fe7bbde33de18a428baf84ee9d2678f66913/package.json#L49

That was the same problem we had for levelgraph-jsonld.

**Comment by BigBlueHat** [comment]
@mcollina sorry for the wait! ⌚️

**Pull request merged**
